<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>aps-api</artifactId>
        <groupId>com.zlt.aps</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zlt.aps.cd15</groupId>
    <artifactId>aps-cd15-api</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>cd15-api</name>
    <description>15度裁断工序api</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-core</artifactId>
        </dependency>

        <!--   通用模块 DTO     -->
        <dependency>
            <groupId>com.zlt.aps</groupId>
            <artifactId>aps-common-core</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.zlt</groupId>
                    <artifactId>zlt-module-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>