-- 垫胶排产参数数据同步脚本
-- 对应实体：DjParams (T_DJ_PARAMS)
-- PARAM_CODE 使用 SYS1401XXX 格式，编码规则：SYS + 工序号(14) + 分组号(01) + 3位流水号
-- 执行日期：2026-06-22

-- ==================== 基础参数 ====================

-- SYS1401001 卷曲标准长度（米/卷）
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401001', '卷曲标准长度（米/卷）', '84', 1, '84', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401001');

-- SYS1401002 工装（台车）总数
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401002', '工装（台车）总数', '10', 1, '10', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401002');

-- SYS1401003 整车率
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401003', '整车率', '0.8', 1, '0.8', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401003');

-- ==================== 排产参数 ====================

-- SYS1401004 成型机台数与排产深度映射
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401004', '成型机台数与排产深度映射', '1:4', 1, '1:4', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401004');

-- SYS1401005 安全水位线（个班次）
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401005', '安全水位线（个班次）', '2', 1, '2', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401005');

-- SYS1401006 停产天数阈值（天）
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401006', '停产天数阈值（天）', '2', 1, '2', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401006');

-- SYS1401007 全局默认损耗率
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401007', '全局默认损耗率', '0', 1, '0', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401007');

-- SYS1401008 切换口型时长（小时）
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401008', '切换口型时长（小时）', '0.5', 1, '0.5', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401008');

-- SYS1401009 切换胶料时长（小时）
INSERT INTO `t_dj_params` (`FACTORY_CODE`, `PRODUCT_TYPE_CODE`, `PARAM_CODE`, `PARAM_NAME`, `PARAM_VALUE`, `DATA_TYPE`, `DEFAULE_VALUE`, `BUSINESS_GROUP`, `IS_SHOW`)
SELECT '116', 'TBR', 'SYS1401009', '切换胶料时长（小时）', '1.0', 1, '1.0', '1401', 1
WHERE NOT EXISTS (SELECT 1 FROM `t_dj_params` WHERE `FACTORY_CODE` = '116' AND `PARAM_CODE` = 'SYS1401009');
