-- 胎胚施工信息表 - 新增半部件物料名
-- 表名: T_MDM_CONSTRUCTION_INFO
-- 日期: 2026-06-23
-- 数据库: MySQL

-- 1#胎体布物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `TIRE_FABRIC_NAME1` VARCHAR(200) COMMENT '1#胎体布物料名';

-- 2#胎体布物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `TIRE_FABRIC_NAME2` VARCHAR(200) COMMENT '2#胎体布物料名';

-- 3#胎体布物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `TIRE_FABRIC_NAME3` VARCHAR(200) COMMENT '3#胎体布物料名';

-- 内衬物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `INSIDE_NAME` VARCHAR(200) COMMENT '内衬物料名';

-- 胎侧物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `SIDEWALL_NAME` VARCHAR(200) COMMENT '胎侧物料名';

-- 垫胶物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `PADDING_NAME` VARCHAR(200) COMMENT '垫胶物料名';

-- 零度带束层物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `ZERO_BELT_NAME` VARCHAR(200) COMMENT '零度带束层物料名';

-- 钢丝圈物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BEAD_NAME` VARCHAR(200) COMMENT '钢丝圈物料名';

-- 胎圈物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `TIRE_RING_NAME` VARCHAR(200) COMMENT '胎圈物料名';

-- 1#钢带物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BELT_NAME1` VARCHAR(200) COMMENT '1#钢带物料名';

-- 2#钢带物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BELT_NAME2` VARCHAR(200) COMMENT '2#钢带物料名';

-- 3#钢带物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BELT_NAME3` VARCHAR(200) COMMENT '3#钢带物料名';

-- 4#钢带物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BELT_NAME4` VARCHAR(200) COMMENT '4#钢带物料名';

-- 左加强层物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BELT_CODE_LEFT_NAME` VARCHAR(200) COMMENT '左加强层物料名';

-- 右加强层物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `BELT_CODE_RIGHT_NAME` VARCHAR(200) COMMENT '右加强层物料名';

-- 胎面物料名
ALTER TABLE `T_MDM_CONSTRUCTION_INFO` ADD COLUMN `TREAD_NAME` VARCHAR(200) COMMENT '胎面物料名';
