-- 表名：T_LH_SCHEDULE_RESULT（硫化排程结果表）
-- 日期：2026-08-24
-- 说明：新增硫化排程实时选机排查字段，仅用于结果追踪，不参与排产计算和选机排序。

ALTER TABLE `T_LH_SCHEDULE_RESULT`
    ADD COLUMN `EARLIEST_EMBRYO_AVAILABLE_TIME` DATETIME NULL
        COMMENT '最早胎胚可供硫化时间'
        AFTER `SKU_SORT_DESC`,
    ADD COLUMN `REALTIME_MACHINE_ENDING_INFO` LONGTEXT NULL
        COMMENT '选机时命中机台窗口内前序SKU实时收尾明细'
        AFTER `EARLIEST_EMBRYO_AVAILABLE_TIME`,
    ADD COLUMN `REALTIME_SHIFT_TOTAL_PLAN_QTY` VARCHAR(256) NULL
        COMMENT '新增选机前窗口各班次实时总计划量，格式c1=2000,c2=3000'
        AFTER `REALTIME_MACHINE_ENDING_INFO`,
    ADD COLUMN `REALTIME_SHIFT_CHANGEOVER_COUNT` VARCHAR(256) NULL
        COMMENT '新增选机前窗口各班次实时换模和换活字块次数'
        AFTER `REALTIME_SHIFT_TOTAL_PLAN_QTY`,
    ADD COLUMN `REALTIME_STRUCTURE_SCHEDULED_MACHINE_COUNT` VARCHAR(128) NULL
        COMMENT '新增选机前当前结构按排程日实时已排硫化机台数'
        AFTER `REALTIME_SHIFT_CHANGEOVER_COUNT`,
    ADD COLUMN `SKU_MACHINE_SELECTION_DESC` LONGTEXT NULL
        COMMENT '新增SKU选机候选顺序、正式可开产时间及软排序指标描述'
        AFTER `REALTIME_STRUCTURE_SCHEDULED_MACHINE_COUNT`,
    ADD COLUMN `SKU_REALTIME_SELECTION_ORDER` VARCHAR(256) NULL
        COMMENT '新增SKU按排程日真实命中选机顺序，格式T=1,T+1=3'
        AFTER `SKU_MACHINE_SELECTION_DESC`;
