-- 垫胶施工信息表增加垫胶胶料和垫胶长度字段
-- 对应实体：MdmConstructionInfo 新增字段 paddingRubber(PADDING_RUBBER)、paddingLength(PADDING_LENGTH)
-- 执行日期：2026-06-18

ALTER TABLE T_MDM_CONSTRUCTION_INFO ADD PADDING_RUBBER VARCHAR2(50) DEFAULT NULL;
COMMENT ON COLUMN T_MDM_CONSTRUCTION_INFO.PADDING_RUBBER IS '垫胶胶料';

ALTER TABLE T_MDM_CONSTRUCTION_INFO ADD PADDING_LENGTH NUMBER(18,2) DEFAULT NULL;
COMMENT ON COLUMN T_MDM_CONSTRUCTION_INFO.PADDING_LENGTH IS '垫胶长度';
