-- 胎面TM模块CRUD菜单权限
-- 父级ID: 4

-- 主菜单：胎面参数设置
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面参数设置', 150, 10, 'menuItem', '/tm/tmParams', '#', 'tm/params/index', 1, 0, 'M', '0', '0', 'tm:tmParams:view', '', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"胎面参数设置\",\"en_US\":\"TM Parameter Setting\"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
-- 查询
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmParams:query', 'tm:tmParams:list', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"查询\",\"en_US\":\"Query\"}]', NULL, NULL);
-- 新增
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmParams:add', 'tm:tmParams:add', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"新增\",\"en_US\":\"Add\"}]', NULL, NULL);
-- 修改
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmParams:edit', 'tm:tmParams:edit', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"修改\",\"en_US\":\"Edit\"}]', NULL, NULL);
-- 删除
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmParams:remove', 'tm:tmParams:remove', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"删除\",\"en_US\":\"Delete\"}]', NULL, NULL);
-- 导出
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmParams:export', 'tm:tmParams:export', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"导出\",\"en_US\":\"Export\"}]', NULL, NULL);
-- 导入
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmParams:import', 'tm:tmParams:import', '#', '#', 'admin', '2025-12-12 10:00:00', 'admin', '2025-12-12 10:00:00', NULL, '[{\"zh_CN\":\"导入\",\"en_US\":\"Import\"}]', NULL, NULL);
-- 主菜单：胎面胶料与机台关系
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面胶料与机台关系', 4, 10, 'menuItem', '/tm/tmGlueMachineReal', '#', 'tm/glueMachineReal/index', 1, 0, 'M', '0', '0', 'tm:tmGlueMachineReal:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面胶料与机台关系","en_US":"Glue Machine Relationship"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
-- 查询
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueMachineReal:query', 'tm:tmGlueMachineReal:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
-- 新增
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueMachineReal:add', 'tm:tmGlueMachineReal:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
-- 修改
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueMachineReal:edit', 'tm:tmGlueMachineReal:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
-- 删除
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueMachineReal:remove', 'tm:tmGlueMachineReal:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
-- 导出
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueMachineReal:export', 'tm:tmGlueMachineReal:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
-- 导入
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueMachineReal:import', 'tm:tmGlueMachineReal:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 1. TmMachineInfo - TM0803
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面机台基础信息', 4, 10, 'menuItem', '/tm/tmMachineInfo', '#', 'tm/machineInfo/index', 1, 0, 'M', '0', '0', 'tm:tmMachineInfo:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面机台基础信息","en_US":"Machine Info"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineInfo:query', 'tm:tmMachineInfo:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineInfo:add', 'tm:tmMachineInfo:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineInfo:edit', 'tm:tmMachineInfo:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineInfo:remove', 'tm:tmMachineInfo:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineInfo:export', 'tm:tmMachineInfo:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineInfo:import', 'tm:tmMachineInfo:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 2. TmMachineMaintenance - TM0804
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面机台维修计划', 4, 20, 'menuItem', '/tm/tmMachineMaintenance', '#', 'tm/machineMaintenance/index', 1, 0, 'M', '0', '0', 'tm:tmMachineMaintenance:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面机台维修计划","en_US":"Machine Maintenance"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineMaintenance:query', 'tm:tmMachineMaintenance:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineMaintenance:add', 'tm:tmMachineMaintenance:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineMaintenance:edit', 'tm:tmMachineMaintenance:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineMaintenance:remove', 'tm:tmMachineMaintenance:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineMaintenance:export', 'tm:tmMachineMaintenance:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineMaintenance:import', 'tm:tmMachineMaintenance:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 3. TmMachineSpeed - TM0805
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面机台生产速度管理', 4, 30, 'menuItem', '/tm/tmMachineSpeed', '#', 'tm/machineSpeed/index', 1, 0, 'M', '0', '0', 'tm:tmMachineSpeed:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面机台生产速度管理","en_US":"Machine Speed"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineSpeed:query', 'tm:tmMachineSpeed:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineSpeed:add', 'tm:tmMachineSpeed:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineSpeed:edit', 'tm:tmMachineSpeed:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineSpeed:remove', 'tm:tmMachineSpeed:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineSpeed:export', 'tm:tmMachineSpeed:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMachineSpeed:import', 'tm:tmMachineSpeed:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 4. TmMouthPlate - TM0806
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面口型板信息', 4, 40, 'menuItem', '/tm/tmMouthPlate', '#', 'tm/mouthPlate/index', 1, 0, 'M', '0', '0', 'tm:tmMouthPlate:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面口型板信息","en_US":"Mouth Plate"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMouthPlate:query', 'tm:tmMouthPlate:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMouthPlate:add', 'tm:tmMouthPlate:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMouthPlate:edit', 'tm:tmMouthPlate:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMouthPlate:remove', 'tm:tmMouthPlate:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMouthPlate:export', 'tm:tmMouthPlate:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmMouthPlate:import', 'tm:tmMouthPlate:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 5. TmSpecifyMachine - TM0807
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面定点与禁排机台规则', 4, 50, 'menuItem', '/tm/tmSpecifyMachine', '#', 'tm/specifyMachine/index', 1, 0, 'M', '0', '0', 'tm:tmSpecifyMachine:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面定点与禁排机台规则","en_US":"Specify Machine"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmSpecifyMachine:query', 'tm:tmSpecifyMachine:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmSpecifyMachine:add', 'tm:tmSpecifyMachine:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmSpecifyMachine:edit', 'tm:tmSpecifyMachine:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmSpecifyMachine:remove', 'tm:tmSpecifyMachine:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmSpecifyMachine:export', 'tm:tmSpecifyMachine:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmSpecifyMachine:import', 'tm:tmSpecifyMachine:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 6. TmGlueGroupOrder - TM0808
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面胶料组顺序', 4, 60, 'menuItem', '/tm/tmGlueGroupOrder', '#', 'tm/glueGroupOrder/index', 1, 0, 'M', '0', '0', 'tm:tmGlueGroupOrder:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面胶料组顺序","en_US":"Glue Group Order"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueGroupOrder:query', 'tm:tmGlueGroupOrder:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueGroupOrder:add', 'tm:tmGlueGroupOrder:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueGroupOrder:edit', 'tm:tmGlueGroupOrder:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueGroupOrder:remove', 'tm:tmGlueGroupOrder:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueGroupOrder:export', 'tm:tmGlueGroupOrder:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueGroupOrder:import', 'tm:tmGlueGroupOrder:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 7. TmGlueOrder - TM0809
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面胶料顺序', 4, 70, 'menuItem', '/tm/tmGlueOrder', '#', 'tm/glueOrder/index', 1, 0, 'M', '0', '0', 'tm:tmGlueOrder:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面胶料顺序","en_US":"Glue Order"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueOrder:query', 'tm:tmGlueOrder:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueOrder:add', 'tm:tmGlueOrder:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueOrder:edit', 'tm:tmGlueOrder:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueOrder:remove', 'tm:tmGlueOrder:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueOrder:export', 'tm:tmGlueOrder:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmGlueOrder:import', 'tm:tmGlueOrder:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 8. TmLossSetting - TM0810
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面损耗率设定信息', 4, 80, 'menuItem', '/tm/tmLossSetting', '#', 'tm/lossSetting/index', 1, 0, 'M', '0', '0', 'tm:tmLossSetting:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面损耗率设定信息","en_US":"Loss Rate Setting"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmLossSetting:query', 'tm:tmLossSetting:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmLossSetting:add', 'tm:tmLossSetting:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmLossSetting:edit', 'tm:tmLossSetting:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmLossSetting:remove', 'tm:tmLossSetting:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmLossSetting:export', 'tm:tmLossSetting:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmLossSetting:import', 'tm:tmLossSetting:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 9. TmCurlRoll - TM0811
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面卷曲长度', 4, 90, 'menuItem', '/tm/tmCurlRoll', '#', 'tm/curlRoll/index', 1, 0, 'M', '0', '0', 'tm:tmCurlRoll:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面卷曲长度","en_US":"Curl Roll"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmCurlRoll:query', 'tm:tmCurlRoll:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmCurlRoll:add', 'tm:tmCurlRoll:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmCurlRoll:edit', 'tm:tmCurlRoll:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmCurlRoll:remove', 'tm:tmCurlRoll:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmCurlRoll:export', 'tm:tmCurlRoll:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmCurlRoll:import', 'tm:tmCurlRoll:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 10. TmStock - TM0812
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面库存', 4, 100, 'menuItem', '/tm/tmStock', '#', 'tm/stock/index', 1, 0, 'M', '0', '0', 'tm:tmStock:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面库存","en_US":"Stock"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStock:query', 'tm:tmStock:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStock:add', 'tm:tmStock:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStock:edit', 'tm:tmStock:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStock:remove', 'tm:tmStock:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStock:export', 'tm:tmStock:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStock:import', 'tm:tmStock:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 11. TmShiftConfig - TM0813
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面班制配置', 4, 110, 'menuItem', '/tm/tmShiftConfig', '#', 'tm/shiftConfig/index', 1, 0, 'M', '0', '0', 'tm:tmShiftConfig:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面班制配置","en_US":"Shift Config"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmShiftConfig:query', 'tm:tmShiftConfig:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmShiftConfig:add', 'tm:tmShiftConfig:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmShiftConfig:edit', 'tm:tmShiftConfig:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmShiftConfig:remove', 'tm:tmShiftConfig:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmShiftConfig:export', 'tm:tmShiftConfig:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmShiftConfig:import', 'tm:tmShiftConfig:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 12. TmDepthConfig - TM0816
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('备库班数配置', 150, 120, 'menuItem', '/tm/depthConfig', '#', 'tm/depthConfig/index', 1, 0, 'M', '0', '0', 'tm:depthConfig:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"备库班数配置","en_US":"Stock Reserve Shift Config"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:depthConfig:query', 'tm:depthConfig:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('新增', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:depthConfig:add', 'tm:depthConfig:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"新增","en_US":"Add"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('修改', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:depthConfig:edit', 'tm:depthConfig:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"修改","en_US":"Edit"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('删除', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:depthConfig:remove', 'tm:depthConfig:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStockCoverClass:export', 'tm:tmStockCoverClass:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导入', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmStockCoverClass:import', 'tm:tmStockCoverClass:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import"}]', NULL, NULL);

-- 胎面调度员操作日志主菜单
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面调度员操作日志', 4, 120, 'menuItem', '/tm/tmDispatcherLog', '#', 'tm/dispatcherLog/index', 1, 0, 'M', '0', '0', 'tm:tmDispatcherLog:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面调度员操作日志","en_US":"Tread Dispatcher Log"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
-- 查询
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmDispatcherLog:query', 'tm:tmDispatcherLog:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query"}]', NULL, NULL);
-- 导出
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('导出', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmDispatcherLog:export', 'tm:tmDispatcherLog:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export"}]', NULL, NULL);

-- 胎面排程结果
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
('胎面排程结果', 4, 130, 'menuItem', '/tm/tmScheduleResult', '#', 'tm/scheduleResult/index', 1, 0, 'M', '0', '0', 'tm:tmScheduleResult:view', '', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"胎面排程结果","en_US":"Tread Schedule Result","vi_VN":"Kết quả lịch trình mặt lốp"}]', NULL, NULL);
SET @parentId = LAST_INSERT_ID();
-- 查询
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('查询列表', @parentId, 10, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:query', 'tm:tmScheduleResult:list', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"查询","en_US":"Query","vi_VN":"Truy vấn"}]', NULL, NULL);
-- 插单
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('插单', @parentId, 20, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:add', 'tm:tmScheduleResult:add', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"插单","en_US":"Insert Order","vi_VN":"Thêm đơn hàng"}]', NULL, NULL);
-- 调量
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('调量', @parentId, 30, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:edit', 'tm:tmScheduleResult:edit', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"调量","en_US":"Adjust Qty","vi_VN":"Điều chỉnh số lượng"}]', NULL, NULL);
-- 转机台
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('转机台', @parentId, 40, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:changeMachine', 'tm:tmScheduleResult:changeMachine', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"转机台","en_US":"Change Machine","vi_VN":"Chuyển máy"}]', NULL, NULL);
-- 删除
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('删除', @parentId, 50, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:remove', 'tm:tmScheduleResult:remove', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"删除","en_US":"Delete","vi_VN":"Xóa"}]', NULL, NULL);
-- 导出
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('导出', @parentId, 60, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:export', 'tm:tmScheduleResult:export', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导出","en_US":"Export","vi_VN":"Xuất"}]', NULL, NULL);
-- 导入
INSERT INTO `sys_menu` (`MENU_NAME`, `PARENT_ID`, `ORDER_NUM`, `TARGET`, `PATH`, `BT_URL`, `COMPONENT`, `IS_FRAME`, `IS_CACHE`, `MENU_TYPE`, `VISIBLE`, `STATUS`, `PERMS`, `BT_PERMS`, `ICON`, `BT_ICON`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`, `REMARK`, `LANG_JSON`, `IS_REFRESH`, `QUERY`) VALUES
    ('导入', @parentId, 70, 'menuItem', '#', '#', NULL, 1, 0, 'F', '0', '0', 'tm:tmScheduleResult:import', 'tm:tmScheduleResult:import', '#', '#', 'admin', NOW(), 'admin', NOW(), NULL, '[{"zh_CN":"导入","en_US":"Import","vi_VN":"Nhập"}]', NULL, NULL);
