<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>3.5.2-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zlt.aps</groupId>
    <artifactId>aps-engine</artifactId>
    <version>1.0.3-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>aps-engine-mp-core</module>
        <module>aps-engine-tm-core</module>
        <module>aps-engine-cd15-core</module>
        <module>aps-engine-cd90-core</module>
<!--        <module>aps-engine-cx-core</module>-->
        <module>aps-engine-gdyy-core</module>
        <module>aps-engine-gsq-core</module>
        <module>aps-engine-nc-core</module>
        <module>aps-engine-tc-core</module>
        <module>aps-engine-tq-core</module>
        <module>aps-engine-xwyy-core</module>
        <module>aps-engine-tm</module>
<!--        <module>aps-engine-cx</module>-->
        <module>aps-engine-tc</module>
        <module>aps-engine-nc</module>
        <module>aps-engine-cd15</module>
        <module>aps-engine-cd90</module>
        <module>aps-engine-gdyy</module>
        <module>aps-engine-xwyy</module>
        <module>aps-engine-tq</module>
        <module>aps-engine-gsq</module>
        <module>mix-engine-schedule</module>
        <module>mix-engine-setting</module>
        <module>mix-plat-engine-schedule-core</module>
    </modules>
</project>