<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi-bootui</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>4.5.2-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zlt</groupId>
    <artifactId>zlt-modules</artifactId>

    <packaging>pom</packaging>
    <modules>
        <module>zlt-ui-kettle</module>
        <module>zlt-cas-client</module>
        <module>zlt-frame-core</module>
    </modules>

</project>