<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zlt.aps</groupId>
        <artifactId>aps-modules</artifactId>
        <version>1.0.3-SNAPSHOT</version>
    </parent>

    <artifactId>aps-itf</artifactId>
    <name>aps-itf</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- TLT框架启动包 -->
        <dependency>
            <groupId>com.zlt</groupId>
            <artifactId>zlt-module-starter</artifactId>
        </dependency>
        <!-- 使用第三方swagger的ui  范围地址：http://localhost:8080/doc.html -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zlt.aps</groupId>
            <artifactId>aps-base</artifactId>
        </dependency>

        <!-- 操作日志jar -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zlt.aps.itf</groupId>
            <artifactId>aps-itf-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zlt</groupId>
            <artifactId>zlt-rabbitMQ</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.zlt.aps</groupId>
            <artifactId>aps-maindata</artifactId>
        </dependency>
        
        <!-- log4j-slf4j-impl cannot be present with log4j-to-slf4j 报错 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-slf4j-impl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-jul</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>jul-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <snapshotRepository>
            <id>local-snapshot</id>
            <url>http://192.168.2.95:8081/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>

        <repository>
            <id>local-release</id>
            <url>http://192.168.2.95:8081/nexus/content/repositories/releases/</url>
        </repository>

    </distributionManagement>

    <repositories>
        <repository>
            <id>local-snapshot</id>
            <url>http://192.168.2.95:8081/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <!-- 默认不下载快照版本，这里开启下载快照版本到本地仓库 -->
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>


</project>
