spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.2.101:1521/zlt
    username: LL_APS_TEST
    password: LL_APS_TEST
    driverClassName: oracle.jdbc.driver.OracleDriver
    hikari:
      connectionTimeout: 120000
      maximumPoolSize: 2500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    database: 1
    host: 192.168.2.92
    port: 6379
    password:
#引用包时，要加入的配置参数，否则找不到mapper
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    com.zlt.aps.common.engine.mapper: DEBUG
i18n_msg:
  baseName: none
server:
  port: 8899
mq:
  scheduleLog:
    queue: dev.schedule.cx.log.queue
    exchange: dev.schedule.cx.log.exchange
    rutekey: dev.schedule.cx.log.rutekey