-- 日期：2026-07-10
-- 说明：胎面调度日志表新增单步撤销支持字段。
-- 部署要求：发布包含撤销功能的 aps-tm 服务前执行本脚本。

ALTER TABLE `T_TM_DISPATCHER_LOG` ADD COLUMN `UNDO_STATUS` VARCHAR(1) DEFAULT '0' COMMENT '撤销状态：0-未撤销、1-已撤销';
ALTER TABLE `T_TM_DISPATCHER_LOG` ADD COLUMN `AFFECTED_BEFORE_JSON` LONGTEXT COMMENT '受影响结果操作前快照JSON';
ALTER TABLE `T_TM_DISPATCHER_LOG` ADD COLUMN `AFFECTED_AFTER_JSON` LONGTEXT COMMENT '受影响结果操作后快照JSON';