<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>ruoyi</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>2.2.2-SNAPSHOT</version>
    </parent>

    <packaging>pom</packaging>
    <modules>
        <module>aps-tm</module>
        <module>aps-lh</module>
        <module>aps-cx</module>
        <module>aps-tc</module>
        <module>aps-nc</module>
        <module>aps-cd15</module>
        <module>aps-cd90</module>
        <module>aps-gdyy</module>
        <module>aps-xwyy</module>
        <module>aps-tq</module>
        <module>aps-gsq</module>
        <module>aps-mps</module>
    </modules>

    <groupId>com.zlt.aps</groupId>
    <artifactId>aps-modules</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <!-- 依赖声明 -->
    <dependencyManagement>
        <dependencies>
            <!-- APS公共模块 -->
            <dependency>
                <groupId>com.zlt.aps</groupId>
                <artifactId>aps-common-core</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <!-- APS的API模块 -->
            <dependency>
                <groupId>com.zlt.aps.cd15</groupId>
                <artifactId>aps-cd15-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.cd90</groupId>
                <artifactId>aps-cd90-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.cx</groupId>
                <artifactId>aps-cx-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.gdyy</groupId>
                <artifactId>aps-gdyy-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.gsq</groupId>
                <artifactId>aps-gsq-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.lh</groupId>
                <artifactId>aps-lh-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.nc</groupId>
                <artifactId>aps-nc-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.tc</groupId>
                <artifactId>aps-tc-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.tm</groupId>
                <artifactId>aps-tm-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.tq</groupId>
                <artifactId>aps-tq-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.xwyy</groupId>
                <artifactId>aps-xwyy-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.mps</groupId>
                <artifactId>mps-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>

            <!-- APS的算法引擎模块 -->
            <dependency>
                <groupId>com.zlt.aps.cd15</groupId>
                <artifactId>aps-engine-cd15</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.cd90</groupId>
                <artifactId>aps-engine-cd90</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.cx</groupId>
                <artifactId>aps-engine-cx</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.gdyy</groupId>
                <artifactId>aps-engine-gdyy</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.gsq</groupId>
                <artifactId>aps-engine-gsq</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.lh</groupId>
                <artifactId>aps-engine-lh</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.nc</groupId>
                <artifactId>aps-engine-nc</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.tc</groupId>
                <artifactId>aps-engine-tc</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.tm</groupId>
                <artifactId>aps-engine-tm</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.tq</groupId>
                <artifactId>aps-engine-tq</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt.aps.xwyy</groupId>
                <artifactId>aps-engine-xwyy</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.zlt</groupId>
                <artifactId>zlt-sync-data</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
</project>