<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.zlt.aps</groupId>
        <artifactId>aps-modules</artifactId>
        <version>1.0.3-SNAPSHOT</version>
    </parent>

    <groupId>com.zlt.aps.gsq</groupId>
    <artifactId>aps-gsq</artifactId>
    <version>1.0.3-SNAPSHOT</version>
    <name>aps-gsq</name>
    <description>钢丝圈工序模块</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.zlt</groupId>
            <artifactId>zlt-module-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zlt.aps.gsq</groupId>
            <artifactId>aps-gsq-api</artifactId>
        </dependency>

        <!-- APS公共模块 -->
        <dependency>
            <groupId>com.zlt.aps</groupId>
            <artifactId>aps-common-core</artifactId>
        </dependency>
        <!-- APS基础模块（提供分布式锁等基础设施） -->
        <dependency>
            <groupId>com.zlt.aps</groupId>
            <artifactId>aps-base</artifactId>
        </dependency>
        <!-- 算法引擎模块 -->
        <dependency>
            <groupId>com.zlt.aps.gsq</groupId>
            <artifactId>aps-engine-gsq</artifactId>
        </dependency>
        <!-- 和客户做接口的jar -->
        <dependency>
            <groupId>com.zlt.aps.itf</groupId>
            <artifactId>aps-itf-api</artifactId>
        </dependency>
        <!-- 胎圈排程API（用于钢丝圈排程时回填胎圈排程结果数据） -->
        <dependency>
            <groupId>com.zlt.aps.tq</groupId>
            <artifactId>aps-tq-api</artifactId>
        </dependency>
        <!-- 操作日志jar -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-swagger</artifactId>
        </dependency>
        <!-- APS主数据 -->
        <dependency>
            <groupId>com.zlt.aps</groupId>
            <artifactId>aps-maindata</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <!--
                    1. 加密后,方法体被清空,保留方法参数、注解等信息.主要兼容swagger文档注解扫描
                    2. 方法体被清空后,反编译只能看到方法名和注解,看不到方法体的具体内容
                    3. 加密后的项目需要设置javaagent来启动,启动过程中解密class,完全内存解密,不留下任何解密后的文件
                    4. 启动加密后的jar,生成xxx-encrypted.jar,这个就是加密后的jar文件,加密后不可直接执行
                    5. 无密码启动方式,java -javaagent:xxx-encrypted.jar -jar xxx-encrypted.jar
                    6. 有密码启动方式,java -javaagent:xxx-encrypted.jar='-pwd= 密码' -jar xxx-encrypted.jar
                -->
                <groupId>net.roseboy</groupId>
                <artifactId>classfinal-maven-plugin</artifactId>
                <version>1.2.1</version>
                <configuration>
                    <password>#</password><!-- #表示启动时不需要密码,事实上对于代码混淆来说,这个密码没什么用,它只是一个启动密码 -->
                    <packages>com.zlt</packages><!-- 加密的包名,多个包用逗号分开 -->
                </configuration>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>classFinal</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>