<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.zlt.aps</groupId>
        <artifactId>aps-modules</artifactId>
        <version>1.0.3-SNAPSHOT</version>
    </parent>

    <artifactId>aps-job</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.zlt</groupId>
            <artifactId>zlt-module-starter</artifactId>
        </dependency>
        <!-- 使用第三方swagger的ui  范围地址：http://localhost:8080/doc.html -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
            <version>1.9.6</version>
        </dependency>
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-modules-job</artifactId>
            <version>3.5.2-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.zlt</groupId>
            <artifactId>zlt-kettle</artifactId>
            <version>3.5.2-SNAPSHOT</version>
        </dependency>

        <dependency>
		    <groupId>com.zlt</groupId>
		    <artifactId>zlt-sync-data-api</artifactId>
		    <version>1.0.1-SNAPSHOT</version>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.zlt.aps.itf</groupId>
            <artifactId>aps-itf-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
