<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi-bootui</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>4.5.2-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zlt</groupId>
    <artifactId>zlt-frame-demo-show</artifactId>

    <packaging>jar</packaging>

    <properties>
        <spring-boot.version>2.3.4.RELEASE</spring-boot.version>
        <zlt-frame.version>4.5.2-SNAPSHOT</zlt-frame.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.zlt</groupId>
            <artifactId>zlt-frame-starter</artifactId>
            <version>${zlt-frame.version}</version>
        </dependency>

<!--        示例包，实际工程要去除掉-->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-demo</artifactId>
        </dependency>
    </dependencies>


    <distributionManagement>
        <snapshotRepository>
            <id>local-snapshot</id>
            <url>http://192.168.2.95:8081/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>

        <repository>
            <id>local-release</id>
            <url>http://192.168.2.95:8081/nexus/content/repositories/releases/</url>
        </repository>

    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <fork>true</fork> <!-- 如果没有该配置，devtools不会生效 -->
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <finalName>${project.artifactId}</finalName>

    </build>


</project>