

shiro:
  #使用单点登录时，sso = true
  sso:
    enable: ${shiro-sso-enable}
    cas: ${sso.cas-addr}
    clientName: casClient
    currentCas: ${sso.current-addr}
    loginUrl: ${shiro.sso.cas}/login?service=${sso.current-addr}${shiro.sso.indexUrl}
    logoutUrl: ${shiro.sso.cas}/logout?service=${sso.current-addr}${shiro.sso.indexUrl}
    indexUrl: ${shiro.user.toIndexUrl}
    unauthorizedUrl: ${shiro.user.unauthorizedUrl}
    validateSessionUri: /casTicket/getTicketBySessionId
    aliveTickesUri: /casTicket/getTicketList
    deleteSessionUri: /casTicket/deleteTicketBySessionId
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /error
    # CAS跳转首页地址
    toIndexUrl: /toIndex
    # 首页地址
    indexUrl: /web/index.shtml
    session:
      # Session超时时间，-1代表永不过期（默认30分钟）
      expireTime: 30
spring:
  messages:
    # 国际化资源文件路径
    # 包括common包里面的语言，后端同步，20201202 linbn
    basename: static/i18n/messages,i18n/commonMessages
  #nacos
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: ${nacos.server-addr}
      config:
        # 配置中心地址
        server-addr: ${nacos.server-addr}
        # 配置文件格式
        file-extension: yml
        # 共享配置
        #        shared-dataids: application-aps-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        shared-configs[0]:
          data-id: application-aps-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  redis:
    host: ${redis-addr}
    port: ${redis-port}
    password: ${redis-password}
logging:
  level: debug