# Tomcat
server:
  port: 9066

# 项目相关配置
ruoyi:
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/Telecom/uploadPath
  # 获取ip地址开关
  addressEnabled: true

nacos:
  server-addr: 192.168.10.123:8848
#  server-addr: 127.0.0.1:8848

spring:
  redis:
    host: 192.168.2.93
    port: 6379
    password:
    database: 5
  zipkin:
    baseUrl: "http://192.168.2.93:9411/"
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        namespace: jytest
        group: APS_TEST_GROUP
      config:
        shared-configs[0]:
          data-id: application-aps-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          group: APS_TEST_GROUP
        shared-configs[1]:
          data-id: system-api-prefix-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          group: APS_TEST_GROUP
        refresh-enabled: true
        namespace: jytest
        group: APS_TEST_GROUP
shiro:
  #使用单点登录时，sso = true
  sso:
    #是否需要走单点
    enable: false
    cas: http://192.168.2.93:8899/cas
    clientName: casClient
    currentCas: http://192.168.2.94:9066

#网关配置,只用来取验证码，feignClient使用的是注册中心的网关信息。
gateway:
  url: http://192.168.2.94:9512/
  casUrl: http://192.168.2.93:8899/cas

